import './AppGlobals.css'
import { type Metadata } from 'next'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  icons: {
    apple: '/icon.png',
  },
  manifest: '/manifest.json',
  themeColor: '#000000',
  title: 'Create Next App',
}

export default function RootLayout({ children }: { readonly children: React.ReactNode }): React.JSX.Element {
  return <div className='appLayoutContainer p-4'>{children}</div>
}
