import './AppGlobals.css'
import Header from '@components/app/Header'
import { type Metadata } from 'next'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  icons: {
    apple: '/icon.png',
  },
  manifest: '/manifest.json',
  themeColor: '#000000',
  title: 'Create Next App',
}

export default function RootLayout({ children }: { readonly children: React.ReactNode }): React.JSX.Element {
  return (
    <div className='appLayoutBackground bg-gradient-to-tl from-indigo-50 to-blue-50'>
      <Header />
      <div className='appLayoutContainer p-4'>{children}</div>
    </div>
  )
}
