import './globals.css'
import Header from '@/components/app/Header'
import { Inter } from 'next/font/google'
import { type Metadata } from 'next'
import SessionProvider from '@/contexts/Session'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  description: 'Generated by create next app',
  icons: {
    apple: '/icon.png',
  },
  manifest: '/manifest.json',
  themeColor: '#000000',
  title: 'Create Next App',
}

export default function RootLayout({ children }: { readonly children: React.ReactNode }): React.JSX.Element {
  return (
    <html className={`bg-gradient-to-tl from-indigo-50 to-blue-50 `} lang='en'>
      <body className={`bg-gradient-to-tl from-indigo-50 to-blue-50 ${inter.className}`}>
        <SessionProvider>
          <Header />
          <main className='flex flex-col'>{children}</main>
        </SessionProvider>
      </body>
    </html>
  )
}
