name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: NEXT_PUBLIC_URL_API_AUTH_SERVICES=${{secrets.NEXT_PUBLIC_URL_API_AUTH_SERVICES}} npm run build

      - name: Deploy to production
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEDINVIMA }}
          channelId: live
          projectId: medinvima
