name: CI/CD Workflow

on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  Testing:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
            npm install
            npm run test

  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to production
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEDINVIMA }}'
          channelId: live
          projectId: medinvima
  